version: '3'

services:
  db_dev:
    container_name: ${POSTGRES_DB_NAME}
    image: postgres:15.3
    restart: 'no'
    ports:
      - 5432:5432
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_dev:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  # nextapp_dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3001:3001
  #   env_file: ./.env.development
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
  #     - DATABASE_URL=${DATABASE_URL}
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #   depends_on:
  #     db_dev: 
  #       condition: service_healthy
  #   command: npm run dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next

volumes:
  postgres_dev:
    external: false